# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.forward_x11 = true
  config.vm.synced_folder '.', '/vagrant'
  # VirtualBox.
  # `vagrant up virtualbox --provider=virtualbox`
  config.vm.define "virtualbox" do |virtualbox|
    virtualbox.vm.hostname = "virtualbox-ubuntu1604"
    virtualbox.vm.box = "ubuntu/xenial64"
    virtualbox.vm.network :private_network, ip: "172.16.3.3"

    config.vm.provider :virtualbox do |v|
      v.gui = false 
      v.memory = 1024
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
    
    config.vm.provision "shell", inline: "apt-get update && apt-get -y install gimp"
    config.vm.provision "shell", inline: "apt-get -y install xpdf"
    config.vm.provision "shell", path: "bootstrap.sh"

  end

end
